/* Generated By:JavaCC: Do not edit this line. GLUEQueryParserConstants.java */
package au.edu.sapac.grid.glueschema.transform;

public interface GLUEQueryParserConstants {

  int EOF = 0;
  int EOL = 2;
  int AND = 3;
  int OR = 4;
  int GET = 5;
  int WHERE = 6;
  int GREATERTHAN = 7;
  int LESSERTHAN = 8;
  int NOTEQUAL = 9;
  int EQUAL = 10;
  int GREATEROREQUAL = 11;
  int LESSEROREQUAL = 12;
  int LIKE = 13;
  int AMPERSAND = 14;
  int TRUE = 15;
  int FALSE = 16;
  int LPAREN = 17;
  int RPAREN = 18;
  int STRING = 19;
  int NUMBER = 20;
  int GLUEFIELD = 21;
  int GLUEENTITY = 22;
  int CHAR = 23;
  int DIGIT = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"and\"",
    "\"or\"",
    "\"get\"",
    "\"where\"",
    "\">\"",
    "\"<\"",
    "\"!=\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"like\"",
    "\"&\"",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "<STRING>",
    "<NUMBER>",
    "<GLUEFIELD>",
    "<GLUEENTITY>",
    "<CHAR>",
    "<DIGIT>",
  };

}
